### ISSUE TITLE
Two-in-a-row rule fix

### ISSUE THREAD

**Issue by rkalvait** [Merit-Research/SequentialBLR#1]
In the BLR script, in a section commented as: "# Robust EWMA - two-in-a-row rule applied":
Remove the line of code that sets alrt_counter to zero in the if block for 
    np.abs(Sn) > THRESHOLD and alrt_counter == 1

**Comment by yabskbd** [comment]
Resolved issue in pi_seq_BLR_AVG and pi_seq_BLR_WITH_Sound
